language: python
python:
  - 2.7
  - 3.3
notifications:
  email: false
 
# Setup anaconda
before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.4.2-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.4.2-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - conda info -a
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
#  - sudo rm -rf /dev/shm
#  - sudo ln -s /run/shm /dev/shm
# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose dateutil pandas statsmodels
  # Coverage packages are on my binstar channel
  - conda install --yes -c dan_blanchard python-coveralls nose-cov
  - python setup.py install
 
# Run test
script:
  - nosetests --with-cov --cov gammatools --cov-config .coveragerc --logging-level=INFO
 
# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc

